#!/bin/bash 
script=$(pwd)/../setup.bash
source $script
echo "$(tput bold)$(tput setaf 3)Killing gazebo$(tput sgr0)"
killall gzclient
killall gzserver
echo "$(tput bold)$(tput setaf 3)Compiling plugins$(tput sgr0)"
./compile_plugins
echo "$(tput bold)$(tput setaf 3)Launching gazebo$(tput sgr0)"
lunagazebo
#lunarena
