#!/bin/bash 

################################### Functions ##########################
kill_if_running() {
	[ "$1" = "" ]  && return 0
	pid_to_kill=`pidof $1`
	if [ $pid_to_kill ]
	then
		echo "Killing $1 (pid $pid_to_kill)"
		killall $1
	fi
}

kill_nodes() {
	echo "Cleaning up..."
	kill_if_running "luna_gui_listener"
	kill_if_running "luna_slam"
	kill_if_running "luna_mech_gw"
	kill_if_running "luna_pilot"
	kill_if_running "luna_navigator"
	kill_if_running "luna_gui_gw"
	echo "-------------------------"
}

########################################################################

rebuild=1
in_port="5555"
in_addr=`ifconfig eth0 | grep "inet " | cut -d ':' -f2 | awk '{print $1}'`
out_port="5556"
out_addr="192.168.218.1"

while getopts "a:p:A:P:cdn" opt; 
do	
	case $opt in
	a)	in_addr="$OPTARG";;
	p)	in_port="$OPTARG";;
	A)	out_addr="$OPTARG";;
	P)	out_port="$OPTARG";;
	c)	close=1;;
	d)  clean=1;;
	n)  rebuild=0;;
	\?) echo "Usage: $0 [-d] [-c] [-n] [-a <incomming IP address>] [-p <incomming port>] [-A <outgoing IP address>] [-P <outgoing port>]" >&2; exit 1;;
	esac
done
shift $((OPTIND-1))

if [ $close ]
then
	kill_nodes
else	
	if [ `pgrep -n roscore` ]
	then
		kill_nodes
		if [ $rebuild -eq 1 ]
		then
			if [ $clean ]
			then
				echo "Cleaning targets..."
				cd ~/ROS/pkgs/lunabotics
				make clean
			fi
			echo "Building package..."
			rosmake lunabotics
		fi
		echo "Launching nodes..."
		echo "Using incoming connection $in_addr:$in_port"
		echo "Using outgoing connection $out_addr:$out_port"
		gnome-terminal --tab -t "GUI Listener" -e "bash rosrun lunabotics luna_gui_listener '$in_addr' '$in_port'"
		gnome-terminal --tab -t "GUI Gateway" -e "bash rosrun lunabotics luna_gui_gw '$out_addr' '$out_port'"
		gnome-terminal --tab -t "MECH Gateway" -e "bash rosrun lunabotics luna_mech_gw"
		gnome-terminal --tab -t "SLAM" -e "bash rosrun lunabotics luna_slam"
		gnome-terminal --tab -t "Pilot" -e "bash rosrun lunabotics luna_pilot"
		gnome-terminal --tab -t "Navigator" -e "bash rosrun lunabotics luna_navigator"
		echo "Nodes are up and running. Enjoy! :)"
	else
		echo "roscore is not running!!!"
	fi
fi
