#!/bin/bash 

################################### Functions ##########################
kill_if_running() {
	[ "$1" = "" ]  && return 0
	pid_to_kill=`pidof $1`
	if [ $pid_to_kill ]
	then
		echo "Killing $1 (pid $pid_to_kill)"
		killall -s 2 $1
	fi
}

clrecho() {
	echo "$(tput setaf $1)$(tput bold)$2$(tput sgr0)"
}

kill_nodes() {
	clrecho 3 "Killing nodes..."
	kill_if_running "luna_gui_listener"
	kill_if_running "luna_gui_gw"
	kill_if_running "luna_pilot"
	kill_if_running "luna_navigator"
	kill_if_running "luna_slam"
	kill_if_running "luna_mech_gw"
	kill_if_running "luna_aut_gw"
	kill_if_running "luna_fear"
	echo "-------------------------"
}
	

########################################################################

rebuild=1
in_port="5555"
in_addr=`ifconfig eth0 | grep "inet " | cut -d ':' -f2 | awk '{print $1}'`
out_port="5556"
out_addr="192.168.218.1"

while getopts "a:p:A:P:cdn" opt; 
do	
	case $opt in
	a)	in_addr="$OPTARG";;
	p)	in_port="$OPTARG";;
	A)	out_addr="$OPTARG";;
	P)	out_port="$OPTARG";;
	c)	close=1;;
	d)  clean=1;;
	n)  rebuild=0;;
	\?) echo "$(tput bold)Usage: $0 [-d] [-c] [-n] [-h] [-a <incomming IP address>] [-p <incomming port>] [-A <outgoing IP address>] [-P <outgoing port>]$(tput sgr0)" >&2
		echo ""$(tput sgr0)
		echo "Options:"
		echo "-d					Delete build target before compiling"
		echo "-c					Close running nodes. All other options are ignored when using -c"
		echo "-n					Do not recompile"
		echo "-a ADDR					Specify GUI IP address"
		echo "-A ADDR					Specify IP address for incoming connections"
		echo "-p PORT					Specify GUI TCP port"
		echo "-P ADDR					Specify TCP port for incoming connections"
		exit 1;;
	esac
done
shift $((OPTIND-1))

if [ $close ]
then
	kill_nodes
else	
	if [ `pgrep -n roscore` ]
	then
		kill_nodes
		halt=0
		if [ $rebuild -eq 1 ]
		then
			if [ $clean ]
			then
				clrecho 3 "Cleaning targets..."
				cd ~/ROS/pkgs/lunabotics
				make clean
			fi
			clrecho 3 "Building package..."
			rosmake lunabotics
			halt=$?
		fi
		
		if [ $halt -eq 0 ]
		then
			clrecho 3 "Launching nodes..."
			echo "Using incoming connection $in_addr:$in_port"
			echo "Using outgoing connection $out_addr:$out_port"
			gnome-terminal --tab -t "GUI Gateway" -e "bash rosrun lunabotics luna_gui_gw '$out_addr' '$out_port'" --tab -t "GUI Listener" -e "bash rosrun lunabotics luna_gui_listener '$in_addr' '$in_port'"
			gnome-terminal --tab -t "SLAM" -e "bash rosrun lunabotics luna_slam" --tab -t "Pilot" -e "bash rosrun lunabotics luna_pilot" --tab -t "Navigator" -e "bash rosrun lunabotics luna_navigator" #--tab -t "MECH Gateway" -e "bash rosrun lunabotics luna_mech_gw" --tab -t "AUTSYS Gateway" -e "bash rosrun lunabotics luna_aut_gw" --tab -t "Emergency behavior" -e "bash rosrun lunabotics luna_fear"
			clrecho 2 "Nodes are up and running. Enjoy! :)"
		else
			clrecho 1 "Build failed"
		fi
	else
		clrecho 1 "Roscore is not running!!!"
	fi
fi
